config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root'pages#home'
	get '/software' => 'pages#software'
	get '/services' => 'pages#services'
	get '/support' => 'pages#support'
	get '/news' => 'pages#news'
	get '/aboutUs' => 'pages#aboutUs'
	get '/contact' => 'pages#contact'
	get '/mainframeServices' => 'pages#mainframeServices'
	get '/maintenaceSupport' => 'pages#maintenaceSupport'
	get '/systemSupport' => 'pages#systemSupport'
	get '/ftpSupport' => 'pages#ftpSupport'
	get '/careers' => 'pages#careers'
	get '/partners' => 'pages#partners'
	
	resources :events
	resources :fulltimejobs
	resources :parttimejobs



	resources :forms, only: [:new, :create]
	post '/forms/new', to: 'forms#create'
	




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	belongs_to :form
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :salary
  attribute :location
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "sarah.humphreys59@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/event.rb
class Event < ApplicationRecord




end

app/models/form.rb
class Form < MailForm::Base
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :salary, :validate => true
  attribute :location, :validate => true
  attribute :message, :validate => true
  attribute :attachment, attachment: true



  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Trident Applicant",
      :to => "sarah.humphreys59@gmail.com",
      :from => %("#{name}" <#{email}>),
      
    }
  end

 

end

app/models/fulltimejob.rb
class Fulltimejob < ApplicationRecord
	validates :title, presence: true
  validates :location, presence: true
  validates :details, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/parttimejob.rb
class Parttimejob < ApplicationRecord
	validates :title, presence: true
  validates :location, presence: true
  validates :details, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one :event_id       

	
   ALLOWED_EMAILS = %w[
    sarah.humphreys59@gmail.com
    jaye_cerruti@triserv.com
    tim_humphreys@triserv.com
  ].freeze

  validates :email, inclusion: { in: ALLOWED_EMAILS, message: :invalid }



end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  respond_to :json

  def index
    @events = Event.order(:date) 
    render json: @events
  end  

  def show
    respond_with Event.find(params[:id])
  end

  def create
    respond_with :api, Event.create(event_params)
  end

  def destroy
    respond_with Event.destroy(params[:id])
  end

  def update
    event = Event.find(params['id'])
    event.update(event_params)
    respond_with Event, json: event
  end

  private

  def event_params
    params.permit(
      :id,
      :title,
      :date,
      :event_id,
      :location,
      :details
    )
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

before_action :authenticate_user!, except: :index

	def index
		@events = Event.order(start_date: :asc).where('start_date::date >= CURRENT_DATE')
		@event = Event.new
	end	

	def new
		@event = Event.new
	end	

	def create
		Event.create(event_params)
		redirect_to events_path
	end	

	def edit
		@event = Event.find(params[:id])
	end	


	def update
		@event = Event.find(params[:id])
		@event.update_attributes(event_params)
		redirect_to events_path
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end	


	private

	def event_params
		params.require(:event).permit(:title, :start_date, :end_date, :location, :details)
	end	

	
	

	

end






	

	

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
	
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/fulltimejob_helper.rb
module FulltimejobHelper
end

app/helpers/fulltimejobs_helper.rb
module FulltimejobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="box-edit col-5 offset-3">
  <h1>Edit Your Event</h1>
  <%= simple_form_for @event do |f| %>
    <%= f.input :title %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :location %>
    <%= f.input :details %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div

app/views/events/index.html.erb
<div class="heading" style="position:relative;">
	<h2>Upcoming News & Events</h2>

	<div style="position:absolute;bottom:0;right:0;" class="admin">
		<% if user_signed_in? %>
			<div class="nav-item" style="padding-right:50px;">
				<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %>
			</div>
		<% else %>
			<div class="nav-item" style="padding-right:50px;">
				<%= link_to 'Admin', new_user_session_path, class: 'btn-btn-secondary'  %>
			</div>
		<% end %>
	</div>
</div>

<div class="section animated fadeIn delay-0s">
	<h3><a href="/Press_Release.pdf" target="_blank" class="release">Exit Explorer Press Release</a></h3>
</div>
<hr class="fadeIn delay-2s">
<div class="events section animated fadeIn delay-1s">
	<% if user_signed_in? %>
			<!-- Button trigger modal -->
			<button type="button" class="btn btn-success event-new" data-toggle="modal" data-target="#exampleModal">
				New Event
			</button>
	<% end %>


		<% @events.each do |event| %>
			<div class="event-box" >
					<% if user_signed_in? %>
						<div class="action-btns">
							<%= link_to 'X', event_path(event), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
							<%= link_to 'Edit', edit_event_path(event), class: 'btn btn-primary' %>
						</div>
					<% end %>	
				<h1><%= event.title %></h1>
				<br/>
				<h3><%= event.start_date.strftime("%B %e, %Y") %> - <%= event.end_date.strftime("%B %e, %Y") %></h3>
				<h4>Location: <%= event.location %></h4>
				<p>Details: <%= event.details %></p>
			</div>
		<% end %>	


</div>


<!-- Modal For New Event -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header"  style="background:#022747;">
        <h1 align="center" style="font-size: 25px;">Create New Event</h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color; white;">
          <span aria-hidden="true">x</span>
        </button>
      </div>
      <div class="modal-body" style="background:#022747;">
        
				<%= simple_form_for @event do |f| %>
					<%= f.input :title %>
					<%= f.input :start_date, as: :date, input_html: { class: "datepicker" }%>
					<%= f.input :end_date, as: :date, input_html: { class: "datepicker" }%>
					<%= f.input :location %>
					<%= f.input :details %>
					<br />
					<div align="center">
						<%= f.submit 'Create', class: 'btn btn-primary' %>
					</div>
					<br/>
				<% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<!-- <div class="event-box col-5 offset-3">
	<br/>
	<h1 align="center" style="font-size: 25px;">Create New Event</h1>
	<%= simple_form_for @event do |f| %>
		<%= f.input :title %>
		<%= f.input :start_date, as: :date, input_html: { class: "datepicker" }%>
		<%= f.input :end_date, as: :date, input_html: { class: "datepicker" }%>
		<%= f.input :location %>
		<%= f.input :details %>
		<br />
		<div align="center">
			<%= f.submit 'Create', class: 'btn btn-primary' %>
		</div>
	<% end %>	
	<br/>
</div>

<script>
$('#datepicker').datepicker({format: 'mm-dd-yyyy'});
</script> -->