config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root'pages#home'
	get '/software' => 'pages#software'
	get '/services' => 'pages#services'
	get '/support' => 'pages#support'
	get '/news' => 'pages#news'
	get '/aboutUs' => 'pages#aboutUs'
	get '/contact' => 'pages#contact'
	get '/mainframeServices' => 'pages#mainframeServices'
	get '/maintenaceSupport' => 'pages#maintenaceSupport'
	get '/systemSupport' => 'pages#systemSupport'
	get '/ftpSupport' => 'pages#ftpSupport'
	get '/careers' => 'pages#careers'
	get '/partners' => 'pages#partners'
	
	resources :events
	resources :fulltimejobs
	resources :parttimejobs



	resources :forms, only: [:new, :create]
	post '/forms/new', to: 'forms#create'
	




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	belongs_to :form
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :salary
  attribute :location
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "sarah.humphreys59@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/event.rb
class Event < ApplicationRecord




end

app/models/form.rb
class Form < MailForm::Base
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :salary, :validate => true
  attribute :location, :validate => true
  attribute :message, :validate => true
  attribute :attachment, attachment: true



  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Trident Applicant",
      :to => "sarah.humphreys59@gmail.com",
      :from => %("#{name}" <#{email}>),
      
    }
  end

 

end

app/models/fulltimejob.rb
class Fulltimejob < ApplicationRecord
	validates :title, presence: true
  validates :location, presence: true
  validates :details, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/parttimejob.rb
class Parttimejob < ApplicationRecord
	validates :title, presence: true
  validates :location, presence: true
  validates :details, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one :event_id       

	
   ALLOWED_EMAILS = %w[
    sarah.humphreys59@gmail.com
    jaye_cerruti@triserv.com
    tim_humphreys@triserv.com
  ].freeze

  validates :email, inclusion: { in: ALLOWED_EMAILS, message: :invalid }



end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
	
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trident Services, Inc.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    
  </head>

  <body>

    <div id="flex-content-container">

      <nav class="navbar navbar-toggleable-md navbar-inverse ">
        <div class="logo">
          <%= link_to image_tag('trident.png', :class=>'img-fluid'), root_path %>
        </div>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav ml-auto mt-2 mt-md-0"> 
            <li class="nav-item">
              <%= link_to 'Software', software_path, class: 'navbar-brand' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Services', services_path, class: 'navbar-brand' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Support', support_path, class: 'navbar-brand' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Partners', partners_path, class: 'navbar-brand' %>
            </li>
            <li class="nav-item">
              <%= link_to 'About Us', aboutUs_path, class: 'navbar-brand' %>
            </li>
            <li>
            <%= link_to 'Careers', careers_path, class: 'navbar-brand' %>
          </li>  
          <li class="nav-item">
            <%= link_to 'News', events_path, class: 'navbar-brand' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', contact_path, class: 'navbar-brand' %>
          </li> 
          </ul>
        </div>  
      </nav>


        <% if notice.present? %>
          <p class="alert alert-info"><%= notice %></p>
        <% end %>
        <% if alert.present? %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>


          <%= yield %>
    </div>

    <div id="footer">
      <div class="row-content">

        <div class="footer-item">
          <span><%= image_tag('ibm2.0.jpg', :class => 'footer-pics')%></span>
          <span><%= image_tag('bob.jpg', :class => 'footer-pics')%></span>
          <span><%= image_tag('Destination_z_print.jpg', :class => 'footer-pics') %></span>
          <span><%= image_tag('gsa_logo.jpg', :class => 'footer-pics') %></span>
        </div>
        <div class="footer-item">
          <h5>Trident Services, Inc.</h5>
          <p style="font-size: 19px;">1260 41st Ave, Suite K, 
          <br/>
            Capitola, CA, (831) 465-7661
          </p>
        </div>

      </div>
    </div>
 

  </body>
</html>

app/views/pages/_contact_form.html.erb
<br/>
<div class="application col-lg-5 col-sm-12">
  <br/>
  <u><h2 style="font-size: 30px;" align="center">Please complete the form below</h2></u>
  <br/>
  <%= simple_form_for :contact_form, url: apply_path, method: :post do |f| %>
      <div>
          <%= f.label :name %><br/>
          <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>
          </br>
          <%= f.label :email %><br/>
          <%= f.text_field :email, required: true, class: "contact-form-text-area" %></br>
          </br>
          <%= f.label :location %><br/>
          <%= f.text_field :location, required: true, class: "contact-form-text-area" %></br>
          </br>
          <%= f.label :salary %><br/>
          <%= f.text_field :salary, required: true, class: "contact-form-text-area" %></br>
          </br>
        <%= f.label :message %><br/>
        <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
                          placeholder: "Inlcude extra details"%></br>

        <br/>
        <div align="center">
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %> 
   <br/> 
</div>   

app/views/pages/apply.html.erb
<div class="col-12">
  <div id="contact">
    <%= render 'contact_form' %>
  </div>
</div> 

app/views/pages/careers.html.erb
<div class="heading" style="position:relative">
	<h2>Career Opportunities</h2>
	<div style="position:absolute;bottom:0;right:0;" class="admin">
		<% if user_signed_in? %>
			<div class="nav-item" style="padding-right:50px;" align="right">
					<%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-secondary', style: 'color: grey;' %>
			</div>
		<% else %>
			<div class="nav-item" style="padding-right:50px;" align="right">
				<%= link_to 'Admin', new_user_session_path, class: 'btn-btn-secondary', style: 'color: grey;'  %>
			</div>
		<% end %>
	</div>
</div>
	
<div class="careers section animated fadeIn delay-0s">
	<div class="new-job-action row-content">
		<div class="flex-item">
			<% if user_signed_in? %>
				<!-- Button trigger modal -->
				<button type="button" class="btn btn-success new-job-full" data-toggle="modal" data-target="#fullModal" title="create new full-time job post">
					New Full-time Job
				</button>
			<% end %>
		</div>
		<div class="flex-item">
			<% if user_signed_in? %>
			<!-- Button trigger modal -->
				<button type="button" class="btn btn-success new-job-part" data-toggle="modal" data-target="#partModal" title="create new part-time job post">
					New Part-time Job
				</button>
			<% end %>
		</div>
	</div>
	<div class="row-content">
		<div class="job-list flex-item">
			<h3>Full-Time Positions</h3>
			<% @fulltimejobs.each do |fulltimejob| %>
				<div class="frosty job-post">
					<% if user_signed_in? %>
						<div class="job-actions">
							<%= link_to 'X', fulltimejob_path(fulltimejob), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger', title: 'delete job post' %>
							<%= link_to 'Edit', edit_fulltimejob_path(fulltimejob), class: 'btn btn-primary', title: 'edit job post' %>
						</div>
					<% end %>
					<u><h3><%= link_to fulltimejob.title, fulltimejob_path(fulltimejob)%></h3></u>
					<%= fulltimejob.location %>
				</div>
			<% end %>
		</div>

		<div class="job-list flex-item">
			<h3>Part-Time Positions</h3>
			<% @parttimejobs.each do |parttimejob| %>
				<div class="frosty job-post">
					<% if user_signed_in? %>
						<div class="job-actions">
							<%= link_to 'X', parttimejob_path(parttimejob), method: :delete, data: {confirm: 'Are you sure you want to  delete this?'}, class: 'btn btn-danger', title: 'delete job post'  %>
							<%= link_to 'Edit', edit_parttimejob_path(parttimejob), class: 'btn btn-primary', title: 'edit job post' %>
						</div>
					<% end %>
					<u><h3><%= link_to parttimejob.title, parttimejob_path(parttimejob) %></h3></u>
					<h4><%= parttimejob.location %></h4>
				</div>
			<% end %>	
		</div>


	</div>


</div>

<!-- Modal -->
<div class="modal fade" id="fullModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background:#022747;">
        <h3>New Full-time Job</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="background:#022747;">
         <%= simple_form_for @fulltimejob do |f| %>
						<%= f.input :title %>
						<%= f.input :location %>
						<%= f.input :details %>
						<br />
						<div align="center">
							<%= f.submit 'Create', class: 'btn btn-primary' %>
						</div>
						<br/>
				<% end %>
      </div>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="partModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background:#022747">
        <h3>New Part-time Job</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="background:#022747">
        <%= simple_form_for @parttimejob do |f| %>
					<%= f.input :title %>
					<%= f.input :location %>
					<%= f.input :details %>
					<br />
					<div align="center">
						<%= f.submit 'Create', class: 'btn btn-primary' %>
					</div>
				<% end %>
				<br/>
      </div>
    </div>
  </div>
</div>
      

app/views/pages/contact.html.erb
<div class="heading">
	<h2>Contact Us</h2>
</div>


<div class="section contact">
	<div class="row-content frosty animated fadeIn delay-0s">
		<div class="flex-item contact-info">
			<u><h2>Corporate Office</h2></u>
			<h4>Trident Services, Inc. 
			<br/>
			1260 41st Avenue, Suite K 
			<br/>
			Capitola, CA 95010
			<br/>
			<br/>
			Office Tel: (831) 465-7661 
			<br/>
			Office Fax: (831) 476-0966</h4>
			<br/>
			<a href="mailto:osem@triserv.com" class="link-btn">General Information</a>
		</div>

		<div class="flex-item contact-image">
			<img src="/assets/palm.jpg" class="img">
		</div>
	</div>

	<hr class="fadeIn delay-2s">
	<div class="row-content animated fadeIn delay-1s">
		<div class="flex-item">
			<u><h3>Contact Sales</h3></u>
			<p align="left">
				Our Trident Services sales team is here to help you with any questions you may have about zOSEM & CICS/EM.
				To contact a member of our sales team, follow the link below.
				For questions about our Services offerings, please contact our Services Sales team.</p>
			<p>Sales Telephone: (800) 887- 4336</p>
			<a href="mailto:services@triserv.com" class="link-btn">Email Services Sales</a>
			<a href="mailto:sales@triserv.com" class="link-btn">Email Software Sales</a>

		</div>

		<div class="flex-item support-contact">
			<u><h3>Contact Support</h3></u>
			<p>For support with zOSEM, CICS/EM and ESPS products, please visit our support page.</p>
			<a href="/support" class="link-btn">Visit Support</a>
		</div>
	</div> 
	
</div>





		


				





	 
	

		

			

		
		
			

app/views/pages/ftpSupport.html.erb
<div class="heading">
	<h2>FTP Support</h2>
</div>

<div class="section">
	<h3>The following are instructions on transfering files such as dumps or <br/>screen prints to the Trident FTP site.</h3>
	<div class="row-content">
		<div class="flex-item">
			<ol>
				<li>Start your FTP program and connect to ftp.triserv.com</li>
				<li>Login using your user ID and password provided by Trident Support</li>
				<li>Turn on binary transfer mode using the following command: bin</li>
				<li>You may also want to turn on hash marks so you can see the transfer take place, using the following command: hash</li>
				<li>Now start the stransfer with the put command as follows:
						<br/>
						put your.directory\file.name triserv.file.name
						<br/>
						<br/>
						Use the following file naming conventions:
						pmrcccc.mmmdd.x.typ
						<br/>
						<br/>
						Where pmrcccc is the problem report number assigned to you, such as PMR0786; 
						mmmdd is the current date; 
						<br/>
						x is only used if sending multiple files, then use A through Z
						<br/>
						end with the type of file, use TRS for packed dumps and TXT for any text files.
				</li>
			</ol>
		</div>

		<div class="flex-item">
			<img src="/assets/ftpsession.png" class="image ftp-image" alt="image">
		</div>



	</div>
</div>



	
	

app/views/pages/home.html.erb
<div class="home-banner">
	<div class="frosty">
		<h1 class="animated fadeInLeft">Smart Solutions. Smart Work. Smart Future.</h1>
		<div class=" animated fadeInRight delay-1s">
			<% if @event.present? == true %>
			<br/>
			<u><h2>Upcoming Events</h2></u>
				<h3 style="font-size: 30px;"><%= @event.title %> : <%= @event.start_date.strftime("%B %e, %Y") %> - <%= @event.end_date.strftime("%B %e, %Y") %></h3>
				<h3 style="font-size: 30px;">Location: <%= @event.location %></h3>
			<% end %>	
		</div>	
	</div>
</div>

<div class="section">

	<div class="exit_explorer">
		<h4><a 
			href="/exit_utility.pdf" target="_blank" class="blink">Introducing the new FREE Exit Explorer Utility. <br/>Click to learn more
		</a></h4>
	</div>	

	<div class="row-content">
		<div class="flex-item home-item">
			<u><h3 align="center">Enterprise Software</h3></u>
			<p>Save Time, Money, and Maximize Resources.  
			zOSEM is enabling customers to Reduce and Control ISV Costs, eliminate exit migration issues, and provides an easy to use DFSMShsm optimizer which can dramatically improve HSM performance.</p>
			<a href="/software" class="link-btn">Learn More</a>
		</div>

		<div class="flex-item home-item">
			<u><h3 align="center">IT Consulting</h3></u>
			<p>With an average of over 25 years experience in their individual specialties, let Trident Senior IT Systems Consultants help you get the most out of each IT dollar you spend. We offer a wide spectrum of services to fit our individual clients needs, check out our services for more information.</p>
			<a href="/services" class="link-btn">Learn More</a>
		</div>

	  <div class="flex-item home-item">
	    <u><h3 align="center"> Mainframe Managed Services</h3></u>

			<p>Mainframe Managed Services solutions offer a full take over of Operations, Production Support, Scheduling Support, Security Administration as well as other operational roles.This broad solution includes the more traditional roles such as DBA, Performance/Capacity Management, Technical Project Management, Application performance, Batch/Online performance improvements, High Availability, Disaster Recovery, etc.</p>
			<a href="/services" class="link-btn">Learn More</a>
		</div>
	</div>

	<div class="row-content">
		<div class="flex-item home-item">
			<u><h3 align="center">Contact Support</h3></u>
			<p>With an average of over 25 years experience in their individual specialties, let Trident's Senior IT Systems Consultants help you get the most out of each IT dollar you spend. We offer a wide spectrum of services to fit our individual clients needs, check out our services for more information.</p>
			<a href="/support" class="link-btn">Learn More</a>
			<u><h3 align="center" style="margin-top: 3rem;">Valued Partners</h3></u>
			<a href="/partners" class="link-btn">Learn More</a>
		</div>
		
		<div class="flex-item home-item">
			<u><h3 align="center">In the News</h3></u>
			<p><a href="/ibmsystems2019.pdf" target="_blank">Check out Trident's Tim Humphreys in IBM Systems Magazine for a discussion on the Knowledge Gap facing todays Mainframe shops.</a><br/><br/>
			Trident Services proudly announces the availability of zOSEM 6.2, the latest release of zOperating System Environment Manager. 6.2 brings resource routing at the step level, as well as enhancements to many of our already great features, including our HSM Optimizer and HSM Reporting.
			<br/>
			<br/>
			<div>
				<a href="/62pressrelease.pdf" target="_blank">zOSEM 6.2 Press Release</a>
			</div>
			<div>
				<a href="/zOSEM_Enhancements_Release_6.2.pdf" target="_blank">zOSEM 6.2 Enhancements Document</a></p>
			</div>
		</div>
	</div>

</div>

		
	

app/views/pages/index.html.erb
<div id="root"></div>

app/views/pages/mainframeServices.html.erb
<div class="heading">
	<h2>Mainframe Managed Services</h2>
</div>	

	<br/>
	<p class="manage-serv-info animated fadeIn delay-0s">Our Mainframe Managed Services provides a complete and holistic service offering for your mainframe environment.
	This broad solution includes the more traditional roles such as DBA, Performance/Capacity Management, Technical Project Management, Application performance, Batch/Online performance improvements, High Availability, Disaster Recovery, etc.
	<br/><br/>Our Mainframe Managed Services solution also provides you a means through which we can take over Operations, Production Support, Scheduling Support, Security Administration as well as other operational roles.
	Our goal is to customize a solution for your needs and not try to fit you into a one-size-fits-all model.</p>
	

<div class="environment animated fadeIn delay-1s">
	<div class="environment-image"></div>
	<div class="frosty">
		<h2>The Environment</h2><br/>
		<h4>We designed the Mainframe Managed Services Offering with the following goals in mind:</h4>
		<ul>
			<li>We support all major software configurations.  We have been doing this for so long that we have supported just about every combination of products anyone could come up with.</li>
			<li>We cover the Systems Programming roles as well as those mentioned above.  If you have a special need, please take the time to email us and we will be honest and forthcoming about our ability to support you.</li>
			<li>We provide Application and Operational support - but it is usually from the context of the Technical Support side of the house.  We are here to support any and all teams within your IT organization.</li>
			<li>We offer a la carte choice of services and quantity of hours - and we can change that pretty much on demand.</li>
			<li>Our primary component support includes:</li>
				<ul>
					<li>Operating Systems: z/OS, z/VM, z/Linux, TPF, as well as the z/VSE world</li>
					<li>DB/DC Systems: CICS, DB2, IMS, CA-IDMS, CA-DATACOM-DB (for those still out there), and others</li>
					<li>Tape Management Migrations from CA-TMS, CA-TLMS and ZARA to IBM DFSMSrmm</li>
					<li>DASD Management Migrations from CA-VANTAGE to DFSMS and DFSMShsm</li>
					<li>Non-Disruptive DASD Migration Services from one DASD subsystem to another either local, remote or both</li>
					<li>Tape Migration Services from physical tape to new physical tape technology or Virtual Tape Systems (VTS) local, remote or both   </li>
					<li>Most any past and present ISV product</li>
					<li>If you have a specific need, let us know - if we cannot cover it, we will tell you rather than mislead you and be in trouble when we cannot deliver</li>
				</ul>
			<li>We provide on-call support coverage - it is expected that you would want this from us.</li>		
			<li>We provide Disaster Recovery support - not only testing, but at Disaster Declaration time.</li>		
			<li>We support IBM and non-IBM products and hardware.  We have a very large Wintel/Midrange practice and recognize that we need to interact with the Mainframe for services. </li>		
			<li>We are committed to aligning ourselves with your existing organization - we want to be plug-and-play to minimize disruptions to the organization or service.</li>		
			<li>We provide US-based resources with clearances to meet varying client security requirements.</li>		
			<li>We serve as a vendor agnostic Trusted Advisor.</li>		
			<li>We are committed to providing value-based pricing.</li>		
		</ul>
	</div>
</div>


<div class="section animated fadeIn delay-2s">
 <div class="row-content">

 		<div class="flex-item envi">
			<h3>Take this oppertunity!</h3>
			<p>
				If you have trouble selling staff augmentation to your management team or feel that it is impossible to achieve a winning price point, reach out to us to see how we can help.
				We have worked with a number of clients to help them secure long term support services at price sensitive rates.The Trident Services, Inc.  Mainframe Support Services Offering is a proven, dynamic, and viable solution to satisfy your ever-changing needs
			</p>
		</div>


		<div class="flex-item envi">
			<h3>No strings attached - </h3>
			<p>
				If you will take the time to email us with contact information, needs, requirements, etc. - and provide any form of contact so that we can follow up, our commitment to you is that we will
			</p>
			<ul>
				<li style="font-size: 23px;">Keep your contact information on file for the sole purpose of responding to you - nothing else.  No selling it, no soliciting you again - nothing.</li>
				<li  style="font-size: 23px;">Respond to your request within 24 hours - work days or weekends - it makes no difference to us - we will respond.</li>
				<li  style="font-size: 23px;">Be able to understand your technical requirements - we are not salesmen - we are technical.</li>
				<li  style="font-size: 23px;">Do our best to win your trust and then your business.</li>
			</ul>
		</div>
 </div>

 <div class="row-contentanimated fadeIn delay-2s">
	<div class="flex-item envi" style="text-align:center;">
		<h3>Contact our friendly support staff for more information</h3>
		<b><h4 align="center">
		Telephone: 1 (800) 887-4336
		</h4></b>
		<h5 align="center">or</h5>
		<div align="center">
		<a href="mailto:services@triserv.com" class="btn btn-secondary">Email Support Staff</a>
	</div>
 </div>
</div>

  
     


	

		

	

app/views/pages/maintenaceSupport.html.erb
<div class="heading">
	<h2>Staff Augmentation</h2>
</div>


<div class="section animated fadeIn delay-0s">
	<p>
	One of the challenges facing many IT organizations today is lack of internal resources. Obtaining skilled IT personnel is becoming harder but remains a necessity for supporting our ever changing business environment.<br/><br/> The Trident Staff Augmentation services can help you achieve your business goals by providing skilled personnel with an average of over 25 years experience to work under your direction. This allows organizations to dynamically adjust their staff resources when needed to provide support for projects requiring specialized skills that do not currently exist internally
	</p>
</div>

<div class="staff section blue animated fadeIn delay-1s">
	<div class="frosty">
		<h2 align="center">
		Trident Solution:
		</h2>
		<ul>
			<li  style="font-size: 23px;">We provide skilled professionals to help you manage fluctuating skill needs, allowing you to meet aggressive project deadlines.</li>
			<li style="font-size: 23px;" >We have expertise to fill skill gaps, and we include a knowledge transfer to your staff upon completion.</li>
			<li  style="font-size: 23px;">We help you train your current staff.</li>
		</ul>	
	</div>
</div>		

<div align="center" class="animated fadeIn delay-2s">
	<h4 align="center">Contact our friendly support staff for more information:</h4> 
	<b><h4>
	1 (800) 887-4336
	</h4></b>
	<h5>or</h5>
	<a href="mailto:services@triserv.com" class="btn btn-secondary">Email Support Staff</a>
</div>
		
		